### PR TITLE
ratelimit: expose rate limit via RateLimit-Policy header

### LINKED ISSUE #6: ratelimit: optionally respond with IETF draft Ratelimit-* headers
There's an [IETF draft](https://datatracker.ietf.org/doc/draft-ietf-httpapi-ratelimit-headers/) that defines some HTTP headers `Ratelimit-*` which let the client know about how many requests they can make. This should be configurable.

### PR DESCRIPTION
**Pull request by derhuerst**
closes #6

### CODE REVIEW

**Comment by RussellLuo** [comment]
@derhuerst Thanks for the PR!

Just out of curiosity, is there any real-world use cases where this single `RateLimit-Policy` header might help?

**Comment by derhuerst** [comment]
> Just out of curiosity, is there any real-world use cases where this single `RateLimit-Policy` header might help?

I don't know about any existing production-level systems where `RateLimit-Policy` is being processed in an automated way. I know that the official GitHub API client uses the GitHub API's `x-ratelimit-remaining` & `x-ratelimit-reset` to tell wether & when to retry a request](https://github.com/octokit/plugin-throttling.js/blob/6908daa264ca75b2c4bd145f48754d2c7d063812/src/index.ts#L151-L173).

Personally, I want to adapt my [GTFS-Realtime](https://gtfs.org/realtime/) (transit data, encoded as [protocol buffers](https://developers.google.com/protocol-buffers), served via HTTP) client to respect the rate limit of the server, if it has defined one.

**Comment by derhuerst** [comment]
If I'm not mistaken, the [original draft of the rate limiting HTTP headers](https://datatracker.ietf.org/doc/draft-polli-ratelimit-headers/00/) is from 2019-09-05, so rather new. I hope that more tooling will make use of it in the future.

**Comment by RussellLuo** [comment]
> Personally, I want to adapt my [GTFS-Realtime](https://gtfs.org/realtime/) (...) client to respect the rate limit of the server, if it has defined one.

I think this is a valid point, which will potentially promote cooperation and interaction between clients and servers. So let's give this a try and see how it does :)

**Pull request merged**
